[package]
name = "tlsh_benchmark"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
publish = false

[dependencies]
fastrand = "2.3.0"
fake = { version = "4.3.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
divan = "0.1.21"

fast-tlsh = { version = "0.1.8" }
tlsh2 = { version = "1.0.0", features = ["diff", "fast"] }
simbiota-tlsh = "1.1.1"
tlsh_orig = { git = "https://github.com/dkrisman/tlsh-rs", branch = "main", package = "tlsh" }
ffuzzy = { version = "0.3.16", features = ["unsafe", "unchecked", "unstable"] }

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"

[[bench]]
name = "tlsh_construct_bench"
path = "benches/tlsh_construct_bench.rs"
harness = false

[[bench]]
name = "tlsh_diff_bench"
path = "benches/tlsh_diff_bench.rs"
harness = false